# Generated by Django 6.0.3 on 2026-03-23 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('mission', models.TextField()),
                ('responsibilities', models.TextField()),
                ('contact_channel', models.CharField(help_text='Slack, Teams channel, or email.', max_length=200)),
                ('repository_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('restructured', 'Restructured'), ('disbanded', 'Disbanded')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organization.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('team_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='organization.teamtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='teams.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='teams.team')),
            ],
            options={
                'ordering': ['from_team__name', 'to_team__name'],
                'unique_together': {('from_team', 'to_team', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='Engineer', max_length=80)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('team', 'email')},
            },
        ),
    ]
