# Generated by Django 6.0.3 on 2026-03-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('restructured', 'Restructured'), ('disbanded', 'Disbanded')], default='restructured', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('active', 'Active'), ('restructured', 'Restructured'), ('disbanded', 'Disbanded')], max_length=20)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('restructured', 'Restructured'), ('disbanded', 'Disbanded')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='teams.team')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
